def get_text(lang_code):
    texts = {
        "TR": {
            "theme": "🎨 Ekran Teması",
            "lang": "🌐 Dil",
            "hero_sub": "Teknoloji ile lezzetin buluştuğu nokta • AI destekli akıllı mutfak asistanın",
            "feat_1_title": "Malzemeden Tarif",
            "feat_1_desc": "Elindeki malzemeleri yaz, AIŞef sana yaratıcı bir tarif üretsin.",
            "feat_2_title": "Tarif Sorgula",
            "feat_2_desc": "İstediğin yemeğin adını yaz, malzemeleri ve yapılışını öğren.",
            "feat_3_title": "Sürpriz Tarif",
            "feat_3_desc": "Karar veremiyorsan AIŞef seni şaşırtsın, yepyeni lezzetler keşfet.",
            "feat_4_title": "Kalori & Süre",
            "feat_4_desc": "Her tarifin kalori tahmini ve hazırlama süresi otomatik hesaplanır.",
            "pop_recipes": "🔥 POPÜLER TARİFLER",
            "sidebar_title": "## ⚙️ KONTROL PANELİ",
            "people": "👥 Kaç kişilik?",
            "meal": "🍽️ Öğün:",
            "meal_opts": ["Fark Etmez", "Kahvaltı", "Öğle Yemeği", "Akşam Yemeği", "Atıştırmalık", "Tatlı", "İçecek"],
            "cuisine": "🌍 Mutfak:",
            "cuisine_opts": ["Fark Etmez", "Türk Mutfağı", "İtalyan", "Japon", "Meksika", "Hint", "Çin", "Fransız", "Amerikan", "Kore"],
            "diff": "📊 Zorluk:",
            "diff_opts": ["Fark Etmez", "Kolay (Acemi)", "Orta", "Zor (Şef Seviyesi)"],
            "diet": "🥗 Diyet tercihi:",
            "diet_opts": ["Fark Etmez", "Vejetaryen", "Vegan", "Glutensiz", "Düşük Karbonhidrat", "Yüksek Protein"],
            "show_cal": "🔥 Kalori göster",
            "show_time": "⏱️ Süre göster",
            "history": "## 📜 SON TARİFLER",
            "no_history": "*Henüz tarif üretmediniz.*",
            "sidebar_footer": "AI ile güçlendirilmiş akıllı mutfak asistanı.",
            "tab1": "🍅 Malzemeden Tarif Üret",
            "tab2": "📖 Yemeğin Tarifini Sor",
            "tab3": "🎲 Sürpriz Tarif",
            "tab1_title": "#### 🍅 Elindeki malzemeleri yaz, AIŞef sana tarif üretsin!",
            "tab1_input": "Malzemeleri virgülle ayırarak yaz:",
            "tab1_placeholder": "Örn: 2 yumurta, beyaz peynir, domates, biber, tereyağı",
            "tab1_btn": "🍳 TARİF ÜRET",
            "thinking": "🤖 AIŞef düşünüyor...",
            "tips": "💡 İPUÇLARI",
            "tip1": "Malzemeleri ne kadar detaylı yazarsan (ölçüsüyle), tarif o kadar doğru olur.",
            "tip2": "Baharat ve soslarını da eklemeyi unutma!",
            "tip3": "Buzdolabında kalan ufak malzemeleri bile yaz, AIŞef değerlendirir.",
            "tip4": "Sol panelden kişi sayısı, mutfak tercihi ve diyet ayarlarını yapabilirsin.",
            "tab2_title": "#### 📖 Hangi yemeği yapmak istiyorsun? Adını yaz yeter!",
            "tab2_input": "Yemek adı:",
            "tab2_placeholder": "Örn: Ev yapımı pizza, Fırın sütlaç, Lazanya",
            "tab2_btn": "📖 TARİFİ GETİR",
            "tab2_prep": "tarifini hazırlıyor...",
            "recommended": "🌟 ÖNERİLEN TARİFLER",
            "rec_1": "Türk mutfağının kraliçesi",
            "rec_2": "İtalyan kremamsı pirinç lezzeti",
            "rec_3": "Japon noodle çorbası",
            "rec_4": "Meksika'nın doyurucu sarması",
            "rec_5": "Kore'nin renkli pirinç kasesi",
            "tab3_title": "#### 🎲 Karar veremiyorsan, AIŞef seni şaşırtsın!",
            "tab3_q1": "##### 🍽️ Ne tür bir sürpriz istersin?",
            "tab3_meal": "Öğün seç:",
            "tab3_meal_opts": ["🎲 Tamamen Rastgele", "☀️ Sabah Kahvaltısı", "🌤️ Öğle Yemeği", "🌙 Akşam Yemeği", "🍪 Ara Öğün / Atıştırmalık", "🍰 Tatlı", "🍹 İçecek"],
            "tab3_cuisine": "Mutfak seç:",
            "tab3_cuisine_opts": ["🌍 Herhangi Bir Mutfak", "🇹🇷 Türk", "🇮🇹 İtalyan", "🇯🇵 Japon", "🇲🇽 Meksika", "🇰🇷 Kore", "🇮🇳 Hint", "🇫🇷 Fransız"],
            "lottery_title": "ŞANS ÇEKİLİŞİ",
            "lottery_desc": "Filtreleri seç ve butona bas! AIŞef sana özel bir sürpriz tarif getirsin.",
            "tab3_btn": "🎲 SÜRPRİZ TARİF GETİR",
            "tab3_thinking": "🤖 AIŞef dünyayı dolaşıyor...",
            "tip_title": "🧠 GÜNÜN BİLGİSİ",
            "stats_title": "📊 İSTATİSTİKLER",
            "stats_1": "Toplam <strong>{}</strong> tarif üretildi",
            "stats_2": "Motor: <strong>AI</strong>",
            "stats_3": "Sınırsız tarif çeşidi",
            "footer_1": "Teknoloji ile lezzetin buluştuğu nokta • AI ile güçlendirilmiştir",
            "footer_2": "Yapay zeka ile pişir, farkı hisset 🍳🤖",
            "error_api": "⚠️ API Anahtarı bulunamadı! Lütfen `.env` dosyasına GEMINI_API_KEY değerini girin.",
            "error": "Hata:",
            
            # Prompts
            "p_sys": "Sen yaratıcı ve profesyonel bir şefsin. Adın AIŞef.",
            "p_sys2": "Sen usta bir aşçısın. Adın AIŞef.",
            "p_sys3": "Sen yaratıcı ve sürprizler seven bir şefsin. Adın AIŞef.",
            "p_ingredients": "Kullanıcının elindeki malzemeler:",
            "p_task1": "Bu malzemeleri kullanarak yapabileceği çok lezzetli bir yemek tarifi öner.",
            "p_task2": "Kullanıcı senden '{}' yapmak için detaylı bir tarif istiyor.",
            "p_task3": "Kullanıcıya rastgele, beklemediği, ilginç ve lezzetli bir yemek tarifi öner.\\nSıradan bir yemek olmasın, farklı ve heyecan verici bir şey olsun.",
            "p_person": "kişilik tarif ver.",
            "p_meal": "Öğün türü kesinlikle {} olsun.",
            "p_cuisine": "Mutfak tercihi kesinlikle {} mutfağından olsun.",
            "p_diet": "Diyet tercihi: {}. Buna uygun malzemeler kullan.",
            "p_cal": "Tahmini kalori bilgisini de ekle (porsiyon başına).",
            "p_time": "Tahmini hazırlama ve pişirme süresini de belirt.",
            "p_format1": "Cevabını Markdown formatında ver:\\n### 🍲 [Yemeğin Adı]\\n**⏱️ Hazırlama Süresi:** ...\\n**🔥 Tahmini Kalori:** ... (porsiyon başına)\\n**📊 Zorluk:** Kolay / Orta / Zor\\n**👥 Porsiyon:** {} kişilik\\n\\n#### 🛒 Gerekli Malzemeler\\n(madde madde listele, kullanıcının elinde olmayanları ⚠️ ile işaretle)\\n\\n#### 👨‍🍳 Adım Adım Yapılışı\\n(numaralı, detaylı adımlar)\\n\\n#### 💡 Şefin Püf Noktası\\n(yemeği mükemmel yapacak 1-2 ipucu)\\n\\n#### 🍷 Servis Önerisi\\n(yanında ne gider, nasıl servis edilir)",
            "p_format2": "Cevabını Markdown formatında ver:\\n### 🍽️ {}\\n**📝 Kısa Bilgi:** (yemek hakkında 1-2 cümle, nereden geldiği)\\n**⏱️ Hazırlama Süresi:** ...\\n**🔥 Tahmini Kalori:** ... (porsiyon başına)\\n**📊 Zorluk:** Kolay / Orta / Zor\\n**👥 Porsiyon:** {} kişilik\\n\\n#### 🛒 Gerekli Malzemeler\\n(ölçüleriyle eksiksiz tam liste)\\n\\n#### 👨‍🍳 Adım Adım Yapılışı\\n(numaralı ve detaylı anlatım)\\n\\n#### 💡 Şefin Püf Noktası\\n(yemeği mükemmel yapacak 1-2 ipucu)\\n\\n#### 🍷 Yanında Ne Gider?\\n(bu yemekle uyumlu 1-2 yan öneri)",
            "p_format3": "Cevabını Markdown formatında ver:\\n### 🎲 Sürpriz: [Yemeğin Adı]\\n**🌍 Köken:** (hangi mutfaktan)\\n**⏱️ Hazırlama Süresi:** ...\\n**🔥 Tahmini Kalori:** ... (porsiyon başına)\\n**📊 Zorluk:** Kolay / Orta / Zor\\n**👥 Porsiyon:** {} kişilik\\n\\n#### 🛒 Gerekli Malzemeler\\n(ölçüleriyle tam liste)\\n\\n#### 👨‍🍳 Adım Adım Yapılışı\\n(numaralı ve detaylı)\\n\\n#### 💡 Şefin Püf Noktası\\n(bu özel yemek için ipucu)\\n\\n#### 🤔 Neden Bu Tarif?\\n(neden bu yemeği seçtiğini 1 cümleyle anlat)",
            "g_tip1": ("🧄", "Sarımsağı bıçakla kesmek yerine ezersen aroması 3 kat artar."),
            "g_tip2": ("🧅", "Soğanı kızartmadan önce buzdolabında 10dk beklet, göz yaşartmaz."),
            "g_tip3": ("🍳", "Yumurtayı pişirirken ocağı kısık tutarsan daha yumuşak olur."),
            "g_tip4": ("🥩", "Eti pişirmeden 30dk önce buzdolabından çıkar, eşit pişer."),
            "g_tip5": ("🍝", "Makarna suyuna 1 çay kaşığı zeytinyağı ekle, yapışmaz."),
            "g_tip6": ("🧈", "Tereyağını köpürene kadar kızdır, fındık kokusu yapar."),
            "g_tip7": ("🍚", "Pilav yaparken pirinci 20dk ılık suda beklet, taneli olur."),
            "g_tip8": ("🥗", "Salata sosunu önceden hazırla, malzemeler aromaları çeker."),
            # Yeni Özellikler TR
            "add_fav": "❤️ Favorilere Ekle",
            "remove_fav": "🗑️ Sil",
            "download": "📄 Tarifi İndir",
            "read_aloud": "🔊 Sesli Oku",
            "stop_read": "⏹️ Durdur",
            "fav_title": "❤️ Favorilerim",
            "fav_empty": "Henüz favoriye eklenmiş bir tarifin yok.",
            "cat_all": "Tümü",
            "cat_breakfast": "Kahvaltı",
            "cat_lunch": "Öğle Yemeği",
            "cat_dinner": "Akşam Yemeği",
            "cat_dessert": "Tatlı",
            "cat_drink": "İçecek",
            "cat_other": "Diğer",
            "fav_success": "Tarif favorilere eklendi!",
            "fav_removed": "Tarif silindi!"
        },
        "EN": {
            "theme": "🎨 Theme",
            "lang": "🌐 Language",
            "hero_sub": "Where technology meets taste • Your AI-powered smart kitchen assistant",
            "feat_1_title": "Recipe from Ingredients",
            "feat_1_desc": "Type the ingredients you have, let AIŞef create a creative recipe for you.",
            "feat_2_title": "Search Recipe",
            "feat_2_desc": "Type the name of any dish, learn its ingredients and how to make it.",
            "feat_3_title": "Surprise Recipe",
            "feat_3_desc": "If you can't decide, let AIŞef surprise you and discover new flavors.",
            "feat_4_title": "Calories & Time",
            "feat_4_desc": "Estimated calories and prep time are calculated automatically for every recipe.",
            "pop_recipes": "🔥 POPULAR RECIPES",
            "sidebar_title": "## ⚙️ CONTROL PANEL",
            "people": "👥 How many people?",
            "meal": "🍽️ Meal type:",
            "meal_opts": ["Any", "Breakfast", "Lunch", "Dinner", "Snack", "Dessert", "Beverage"],
            "cuisine": "🌍 Cuisine:",
            "cuisine_opts": ["Any", "Turkish", "Italian", "Japanese", "Mexican", "Indian", "Chinese", "French", "American", "Korean"],
            "diff": "📊 Difficulty:",
            "diff_opts": ["Any", "Easy (Beginner)", "Medium", "Hard (Chef Level)"],
            "diet": "🥗 Diet preference:",
            "diet_opts": ["Any", "Vegetarian", "Vegan", "Gluten-Free", "Low Carb", "High Protein"],
            "show_cal": "🔥 Show calories",
            "show_time": "⏱️ Show time",
            "history": "## 📜 RECENT RECIPES",
            "no_history": "*No recipes generated yet.*",
            "sidebar_footer": "AI-powered smart kitchen assistant.",
            "tab1": "🍅 Recipe from Ingredients",
            "tab2": "📖 Search for a Recipe",
            "tab3": "🎲 Surprise Recipe",
            "tab1_title": "#### 🍅 Write the ingredients you have, let AIŞef generate a recipe!",
            "tab1_input": "Write ingredients separated by commas:",
            "tab1_placeholder": "e.g., 2 eggs, feta cheese, tomatoes, peppers, butter",
            "tab1_btn": "🍳 GENERATE RECIPE",
            "thinking": "🤖 AIŞef is thinking...",
            "tips": "💡 TIPS",
            "tip1": "The more detailed you write the ingredients (with amounts), the more accurate the recipe will be.",
            "tip2": "Don't forget to add your spices and sauces!",
            "tip3": "Even list leftover ingredients in the fridge, AIŞef will make use of them.",
            "tip4": "You can adjust the number of people, cuisine, and diet settings from the left panel.",
            "tab2_title": "#### 📖 Which dish do you want to make? Just write the name!",
            "tab2_input": "Dish name:",
            "tab2_placeholder": "e.g., Homemade pizza, Rice pudding, Lasagna",
            "tab2_btn": "📖 GET RECIPE",
            "tab2_prep": "is preparing the recipe for",
            "recommended": "🌟 RECOMMENDED RECIPES",
            "rec_1": "Queen of Turkish cuisine",
            "rec_2": "Italian creamy rice delight",
            "rec_3": "Japanese noodle soup",
            "rec_4": "Mexico's satisfying wrap",
            "rec_5": "Korea's colorful rice bowl",
            "tab3_title": "#### 🎲 If you can't decide, let AIŞef surprise you!",
            "tab3_q1": "##### 🍽️ What kind of surprise do you want?",
            "tab3_meal": "Select meal:",
            "tab3_meal_opts": ["🎲 Completely Random", "☀️ Breakfast", "🌤️ Lunch", "🌙 Dinner", "🍪 Snack", "🍰 Dessert", "🍹 Beverage"],
            "tab3_cuisine": "Select cuisine:",
            "tab3_cuisine_opts": ["🌍 Any Cuisine", "🇹🇷 Turkish", "🇮🇹 Italian", "🇯🇵 Japanese", "🇲🇽 Mexican", "🇰🇷 Korean", "🇮🇳 Indian", "🇫🇷 French"],
            "lottery_title": "LUCKY DRAW",
            "lottery_desc": "Select filters and press the button! Let AIŞef bring you a special surprise recipe.",
            "tab3_btn": "🎲 GET SURPRISE RECIPE",
            "tab3_thinking": "🤖 AIŞef is traveling the world...",
            "tip_title": "🧠 TIP OF THE DAY",
            "stats_title": "📊 STATISTICS",
            "stats_1": "Total <strong>{}</strong> recipes generated",
            "stats_2": "Engine: <strong>AI</strong>",
            "stats_3": "Unlimited recipe varieties",
            "footer_1": "Where technology meets taste • Powered by AI",
            "footer_2": "Cook with artificial intelligence, feel the difference 🍳🤖",
            "error_api": "⚠️ API Key not found! Please enter the GEMINI_API_KEY in the `.env` file.",
            "error": "Error:",
            
            # Prompts EN
            "p_sys": "You are a creative and professional chef. Your name is AIŞef.",
            "p_sys2": "You are a master chef. Your name is AIŞef.",
            "p_sys3": "You are a creative chef who loves surprises. Your name is AIŞef.",
            "p_ingredients": "The ingredients the user has:",
            "p_task1": "Suggest a very delicious recipe they can make using these ingredients.",
            "p_task2": "The user is asking you for a detailed recipe to make '{}'.",
            "p_task3": "Suggest a random, unexpected, interesting, and delicious recipe to the user.\\nIt shouldn't be an ordinary dish, it should be something different and exciting.",
            "p_person": "Provide a recipe for {} people.",
            "p_meal": "The meal type must be {}.",
            "p_cuisine": "The cuisine must be {}.",
            "p_diet": "Diet preference: {}. Use appropriate ingredients.",
            "p_cal": "Also add estimated calorie information (per serving).",
            "p_time": "Also state the estimated preparation and cooking time.",
            "p_format1": "Provide your answer in Markdown format:\\n### 🍲 [Dish Name]\\n**⏱️ Prep Time:** ...\\n**🔥 Estimated Calories:** ... (per serving)\\n**📊 Difficulty:** Easy / Medium / Hard\\n**👥 Servings:** {} people\\n\\n#### 🛒 Required Ingredients\\n(list bullet points, mark ones the user doesn't have with ⚠️)\\n\\n#### 👨‍🍳 Step-by-Step Instructions\\n(numbered, detailed steps)\\n\\n#### 💡 Chef's Tip\\n(1-2 tips that will make the dish perfect)\\n\\n#### 🍷 Serving Suggestion\\n(what goes well with it, how to serve it)",
            "p_format2": "Provide your answer in Markdown format:\\n### 🍽️ {}\\n**📝 Brief Info:** (1-2 sentences about the dish, where it comes from)\\n**⏱️ Prep Time:** ...\\n**🔥 Estimated Calories:** ... (per serving)\\n**📊 Difficulty:** Easy / Medium / Hard\\n**👥 Servings:** {} people\\n\\n#### 🛒 Required Ingredients\\n(complete list with measurements)\\n\\n#### 👨‍🍳 Step-by-Step Instructions\\n(numbered and detailed explanation)\\n\\n#### 💡 Chef's Tip\\n(1-2 tips that will make the dish perfect)\\n\\n#### 🍷 What goes well with it?\\n(1-2 side suggestions compatible with this dish)",
            "p_format3": "Provide your answer in Markdown format:\\n### 🎲 Surprise: [Dish Name]\\n**🌍 Origin:** (from which cuisine)\\n**⏱️ Prep Time:** ...\\n**🔥 Estimated Calories:** ... (per serving)\\n**📊 Difficulty:** Easy / Medium / Hard\\n**👥 Servings:** {} people\\n\\n#### 🛒 Required Ingredients\\n(full list with measurements)\\n\\n#### 👨‍🍳 Step-by-Step Instructions\\n(numbered and detailed)\\n\\n#### 💡 Chef's Tip\\n(tip for this special dish)\\n\\n#### 🤔 Why This Recipe?\\n(explain in 1 sentence why you chose this dish)",
            "g_tip1": ("🧄", "Crushing garlic instead of chopping it increases its flavor by 3 times."),
            "g_tip2": ("🧅", "Keep onions in the fridge for 10 mins before chopping to avoid tears."),
            "g_tip3": ("🍳", "Keep the heat low when cooking eggs for a softer texture."),
            "g_tip4": ("🥩", "Take meat out of the fridge 30 mins before cooking for even cooking."),
            "g_tip5": ("🍝", "Add 1 tsp of olive oil to pasta water to prevent sticking."),
            "g_tip6": ("🧈", "Heat butter until it foams for a nutty aroma."),
            "g_tip7": ("🍚", "Soak rice in warm water for 20 mins before cooking for fluffy grains."),
            "g_tip8": ("🥗", "Prepare salad dressing in advance to let flavors meld."),
            # Yeni Özellikler EN
            "add_fav": "❤️ Add to Favorites",
            "remove_fav": "🗑️ Remove",
            "download": "📄 Download Recipe",
            "read_aloud": "🔊 Read Aloud",
            "stop_read": "⏹️ Stop",
            "fav_title": "❤️ My Favorites",
            "fav_empty": "You don't have any favorite recipes yet.",
            "cat_all": "All",
            "cat_breakfast": "Breakfast",
            "cat_lunch": "Lunch",
            "cat_dinner": "Dinner",
            "cat_dessert": "Dessert",
            "cat_drink": "Drink",
            "cat_other": "Other",
            "fav_success": "Recipe added to favorites!",
            "fav_removed": "Recipe removed!"
        }
    }
    return texts.get(lang_code, texts["TR"])
